apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::670306365249:user/s3admin
      username: designated_user 
      groups:
        - system:masters